language: elm
cache:
  directories:
    - "client/node_modules"
    - "client/elm-stuff"
    - "client/tests/elm-stuff"
branches:
  except:
  - gh-pages
  - version
install:
  - cd client
  - yarn install
  - yarn elm-app install -y
  - cd -
script:
  - cd client
  - yarn elm-format --validate
  - yarn elm-app test
  - yarn elm-app build
  - echo $(cat build/index.html | sed 's/href="\//herf="/g' | sed 's/src="\//src="/g') > build/index.html
  - cd -
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master