language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - ".lobo"
branches:
  except:
  - version
install:
  - 'yarn install'
  - 'yarn elm-app install'
script:
  - 'yarn test'
  - 'yarn elm-format --validate'
  