language: elm
cache:
  directories:
    - "client/node_modules"
    - "client/elm-stuff"
    - "client/tests/elm-stuff"
branches:
  except:
  - gh-pages
  - version
install:
  - 'yarn install'
  - 'yarn elm-app install -y'
script:
  - 'cd client && yarn elm-format --validate'
  - 'cd client && yarn elm-app test'
  - 'cd client && yarn elm-app build && echo $(cat build/index.html | sed 's/href="\//herf="/g' | sed 's/src="\//src="/g') > build/index.html'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master