language: elm
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - "tests/elm-stuff"
branches:
  except:
  - version
install:
  - 'yarn install'
  - 'yarn elm-app install -y'
script:
  - 'yarn elm-app test'
  - 'yarn format --validate'
  