language: elm
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - ".lobo"
branches:
  except:
  - version
install:
  - 'yarn install'
  - 'yarn elm-app install -y'
script:
  - 'yarn elm-app test'
  - 'yarn elm-format --validate'
  