language: elm
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - "tests/elm-stuff"
branches:
  except:
  - gh-pages
  - version
install:
  - 'yarn install'
  - 'yarn elm-app install -y'
script:
  - 'yarn elm-format --validate'
  - 'yarn elm-app test'
  - 'yarn elm-app build'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
