language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - ".lobo"
branches:
  except:
  - version
install:
  - 'yarn global add elm elm-app'
  - 'yarn install'
  - 'elm-app install -y'
script:
  - 'elm-app test'
  - 'yarn elm-format --validate'
  